# Generated by Django 5.1.5 on 2025-01-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.URLField(default='NaN'),
            preserve_default=False,
        ),
    ]
