# Generated by Django 5.1.4 on 2025-02-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
        ('movies', '0003_remove_movie_image'),
    ]

    operations = [
    ]
