# Generated by Django 5.1.4 on 2025-02-04 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_cartitem'),
        ('movies', '0004_merge_0002_review_0003_remove_movie_image'),
    ]

    operations = [
    ]
