# Generated by Django 5.1.4 on 2025-02-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_merge_20250203_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
